teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 0.5
    scale_linear_turbo:
      x: 1.6

    axis_angular:
      yaw: 0
    scale_angular:
      yaw: 0.4
    scale_angular_turbo:
      yaw: 1.5
    enable_button: 6  # L2 shoulder button
    enable_turbo_button: 7  # R2 shoulder button
